## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df = pd.DataFrame(application_df)
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = pd.DataFrame(application_df)
application_df = application_df.drop(columns = ['EIN', 'NAME'], axis=0)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
applicationtype_counts = application_df['APPLICATION_TYPE'].value_counts()
applicationtype_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 1000
application_types_to_replace = applicationtype_counts[applicationtype_counts < cutoff_value].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_value = classification_counts[classification_counts>1]
classification_value

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`

cutoff_value = 1000

classifications_to_replace = classification_counts[classification_counts < cutoff_value].index


# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
from pandas.core.arrays import categorical
# Convert categorical data to numeric with `pd.get_dummies`
application_numeric = pd.get_dummies(application_df)
application_numeric

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,AFFILIATION_CompanySponsored,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,1,0,0,0,1,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
X = application_numeric.drop('IS_SUCCESSFUL', axis=1)
y = application_numeric['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)


# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 328

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 379
Trainable params: 379
Non-trainable params: 0
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [14]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=50)

Epoch 1/50
804/804 [==============================] - 10s 6ms/step - loss: 0.6274 - accuracy: 0.6824
Epoch 2/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5704 - accuracy: 0.7213
Epoch 3/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5636 - accuracy: 0.7252
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5610 - accuracy: 0.7276
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5594 - accuracy: 0.7284
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5584 - accuracy: 0.7280
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5576 - accuracy: 0.7292
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5569 - accuracy: 0.7298
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5563 - accuracy: 0.7296
Epoch 10/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5558 - accuracy: 0.7303
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5550 - accuracy: 0.7300
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5546 - accuracy: 0.7315
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5541 - accuracy: 0.7310
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5535 - accuracy: 0.7312
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5533 - accuracy: 0.7315
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5532 - accuracy: 0.7320
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5528 - accuracy: 0.7315
Epoch 18/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5527 - accuracy: 0.7319
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5524 - accuracy: 0.7320
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5522 - accuracy: 0.7325
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5517 - accuracy: 0.7322
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5519 - accuracy: 0.7325
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5514 - accuracy: 0.7317
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5516 - accuracy: 0.7322
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5513 - accuracy: 0.7317
Epoch 26/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5512 - accuracy: 0.7318
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5508 - accuracy: 0.7316
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5507 - accuracy: 0.7328
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5506 - accuracy: 0.7320
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5504 - accuracy: 0.7327
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5505 - accuracy: 0.7325
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5502 - accuracy: 0.7317
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5500 - accuracy: 0.7320
Epoch 34/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5501 - accuracy: 0.7328
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7325
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5495 - accuracy: 0.7318
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5500 - accuracy: 0.7326
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5495 - accuracy: 0.7328
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5496 - accuracy: 0.7317
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7317
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7325
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7327
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7327
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7324
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5491 - accuracy: 0.7326
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5492 - accuracy: 0.7321
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7334
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5489 - accuracy: 0.7334
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7321
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5491 - accuracy: 0.7329

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5578 - accuracy: 0.7306 - 496ms/epoch - 2ms/step
Loss: 0.557785153388977, Accuracy: 0.7306122183799744

In [16]:
# Export our model to HDF5 file
nn.save('/OneDrive/Desktop/deep-learning-challenge/Starter_Code/AlphabetSoupCharity_Optimization_3.h5')