## Preprocessing

In [26]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df = pd.DataFrame(application_df)
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [27]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = pd.DataFrame(application_df)
application_df = application_df.drop(columns = ['EIN', 'NAME', 'AFFILIATION', 'USE_CASE', 'ORGANIZATION'], axis=0)
application_df.head()

,APPLICATION_TYPE,CLASSIFICATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,C1000,1,0,N,5000,1
1,T3,C2000,1,1-9999,N,108590,1
2,T5,C3000,1,0,N,5000,0
3,T3,C2000,1,10000-24999,N,6692,1
4,T3,C1000,1,100000-499999,N,142590,1

In [28]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
CLASSIFICATION              71
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [29]:
# Look at APPLICATION_TYPE value counts for binning
applicationtype_counts = application_df['APPLICATION_TYPE'].value_counts()
applicationtype_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [30]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 1000
application_types_to_replace = applicationtype_counts[applicationtype_counts < cutoff_value].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: APPLICATION_TYPE, dtype: int64

In [31]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [32]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_value = classification_counts[classification_counts>1]
classification_value

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [33]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`

cutoff_value = 1000

classifications_to_replace = classification_counts[classification_counts < cutoff_value].index


# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [34]:
from pandas.core.arrays import categorical
# Convert categorical data to numeric with `pd.get_dummies`
application_numeric = pd.get_dummies(application_df)
application_numeric

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,CLASSIFICATION_C1000,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,1,0,0,0,1,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,1,0,0,0,1,...,0,0,0,0,1,0,0,0,1,0

In [35]:
application_numeric.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   STATUS                    34299 non-null  int64
 1   ASK_AMT                   34299 non-null  int64
 2   IS_SUCCESSFUL             34299 non-null  int64
 3   APPLICATION_TYPE_Other    34299 non-null  uint8
 4   APPLICATION_TYPE_T19      34299 non-null  uint8
 5   APPLICATION_TYPE_T3       34299 non-null  uint8
 6   APPLICATION_TYPE_T4       34299 non-null  uint8
 7   APPLICATION_TYPE_T5       34299 non-null  uint8
 8   APPLICATION_TYPE_T6       34299 non-null  uint8
 9   CLASSIFICATION_C1000      34299 non-null  uint8
 10  CLASSIFICATION_C1200      34299 non-null  uint8
 11  CLASSIFICATION_C2000      34299 non-null  uint8
 12  CLASSIFICATION_C2100      34299 non-null  uint8
 13  CLASSIFICATION_C3000      34299 non-null  uint8
 14  CLASSIFICATION_Other      34299 non-null  uint8
 15  INCOME_AMT_0              34299 non-null  uint8
 16  INCOME_AMT_1-9999         34299 non-null  uint8
 17  INCOME_AMT_10000-24999    34299 non-null  uint8
 18  INCOME_AMT_100000-499999  34299 non-null  uint8
 19  INCOME_AMT_10M-50M        34299 non-null  uint8
 20  INCOME_AMT_1M-5M          34299 non-null  uint8
 21  INCOME_AMT_25000-99999    34299 non-null  uint8
 22  INCOME_AMT_50M+           34299 non-null  uint8
 23  INCOME_AMT_5M-10M         34299 non-null  uint8
 24  SPECIAL_CONSIDERATIONS_N  34299 non-null  uint8
 25  SPECIAL_CONSIDERATIONS_Y  34299 non-null  uint8
dtypes: int64(3), uint8(23)
memory usage: 1.5 MB

In [36]:
# Split our preprocessed data into our features and target arrays
X = application_numeric.drop('IS_SUCCESSFUL', axis=1)
y = application_numeric['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [37]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [38]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)


# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 208

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 259
Trainable params: 259
Non-trainable params: 0
_________________________________________________________________

In [39]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [40]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 4s 3ms/step - loss: 0.6635 - accuracy: 0.5998
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6477 - accuracy: 0.6214
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6461 - accuracy: 0.6238
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6451 - accuracy: 0.6219
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6441 - accuracy: 0.6209
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6433 - accuracy: 0.6211
Epoch 7/100
804/804 [==============================] - 3s 4ms/step - loss: 0.6430 - accuracy: 0.6212
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6427 - accuracy: 0.6220
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6422 - accuracy: 0.6215
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6416 - accuracy: 0.6225
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6407 - accuracy: 0.6225
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6403 - accuracy: 0.6225
Epoch 13/100
804/804 [==============================] - 3s 3ms/step - loss: 0.6401 - accuracy: 0.6225
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6398 - accuracy: 0.6220
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6397 - accuracy: 0.6237
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6396 - accuracy: 0.6230
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6395 - accuracy: 0.6234
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6394 - accuracy: 0.6233
Epoch 19/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6393 - accuracy: 0.6241
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6393 - accuracy: 0.6220
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6390 - accuracy: 0.6223
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6390 - accuracy: 0.6240
Epoch 23/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6390 - accuracy: 0.6230
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6389 - accuracy: 0.6254
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6388 - accuracy: 0.6218
Epoch 26/100
804/804 [==============================] - 3s 3ms/step - loss: 0.6387 - accuracy: 0.6225
Epoch 27/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6388 - accuracy: 0.6254
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6388 - accuracy: 0.6245
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6387 - accuracy: 0.6239
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6387 - accuracy: 0.6224
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6386 - accuracy: 0.6242
Epoch 32/100
804/804 [==============================] - 3s 3ms/step - loss: 0.6387 - accuracy: 0.6234
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6385 - accuracy: 0.6226
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6386 - accuracy: 0.6239
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6384 - accuracy: 0.6232
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6385 - accuracy: 0.6246
Epoch 37/100
804/804 [==============================] - 3s 3ms/step - loss: 0.6386 - accuracy: 0.6248
Epoch 38/100
804/804 [==============================] - 3s 3ms/step - loss: 0.6384 - accuracy: 0.6237
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6385 - accuracy: 0.6239
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6385 - accuracy: 0.6244
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6384 - accuracy: 0.6244
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6383 - accuracy: 0.6225
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6383 - accuracy: 0.6237
Epoch 44/100
804/804 [==============================] - 3s 3ms/step - loss: 0.6384 - accuracy: 0.6244
Epoch 45/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6382 - accuracy: 0.6231
Epoch 46/100
804/804 [==============================] - 3s 3ms/step - loss: 0.6383 - accuracy: 0.6244
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6382 - accuracy: 0.6226
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6382 - accuracy: 0.6243
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6383 - accuracy: 0.6237
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6383 - accuracy: 0.6242
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6383 - accuracy: 0.6235
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6383 - accuracy: 0.6244
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6382 - accuracy: 0.6244
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6382 - accuracy: 0.6228
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6382 - accuracy: 0.6236
Epoch 56/100
804/804 [==============================] - 3s 3ms/step - loss: 0.6381 - accuracy: 0.6243
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6382 - accuracy: 0.6254
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6380 - accuracy: 0.6259
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6382 - accuracy: 0.6251
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6380 - accuracy: 0.6243
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6381 - accuracy: 0.6244
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6379 - accuracy: 0.6228
Epoch 63/100
804/804 [==============================] - 3s 4ms/step - loss: 0.6381 - accuracy: 0.6233
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6380 - accuracy: 0.6249
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6380 - accuracy: 0.6247
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6379 - accuracy: 0.6247
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6379 - accuracy: 0.6244
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6381 - accuracy: 0.6262
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6379 - accuracy: 0.6244
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6380 - accuracy: 0.6227
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6379 - accuracy: 0.6239
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6379 - accuracy: 0.6236
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6380 - accuracy: 0.6239
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6380 - accuracy: 0.6256
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6378 - accuracy: 0.6253
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6380 - accuracy: 0.6249
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6380 - accuracy: 0.6228
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6379 - accuracy: 0.6250
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6379 - accuracy: 0.6247
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6378 - accuracy: 0.6248
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6378 - accuracy: 0.6248
Epoch 82/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6380 - accuracy: 0.6242
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6378 - accuracy: 0.6247
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6381 - accuracy: 0.6235
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6379 - accuracy: 0.6238
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6379 - accuracy: 0.6242
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6377 - accuracy: 0.6252
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6378 - accuracy: 0.6250
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6378 - accuracy: 0.6242
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6378 - accuracy: 0.6237
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6379 - accuracy: 0.6228
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6378 - accuracy: 0.6239
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6378 - accuracy: 0.6246
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6379 - accuracy: 0.6237
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6378 - accuracy: 0.6237
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6375 - accuracy: 0.6254
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6377 - accuracy: 0.6233
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6376 - accuracy: 0.6260
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6377 - accuracy: 0.6226
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6377 - accuracy: 0.6250

In [41]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.6428 - accuracy: 0.6209 - 844ms/epoch - 3ms/step
Loss: 0.6427900791168213, Accuracy: 0.6208746433258057

In [42]:
# Export our model to HDF5 file
nn.save('/OneDrive/Desktop/deep-learning-challenge/Starter_Code/AlphabetSoupCharity_Optimization_2.h5')